<?php

namespace PC\DemandeurBundle\Repository;

/**
 * DiagnostiqueResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiagnostiqueResultRepository extends \Doctrine\ORM\EntityRepository
{
}
