pc_demandeur_homepage:
    path:     /
    defaults: { _controller: PCDemandeurBundle:Authentification:index }

pc_demandeur_connexion:
    path: /connect
    defaults: {_controller : PCDemandeurBundle:Authentification:connect }
    
pc_demandeur_resultat:
    path: /result
    defaults: {_controller : PCDemandeurBundle:Diagnostique:calcule}

pc_demandeur_deconnexion:
    path: /deco
    defaults : {_controller: PCDemandeurBundle:Authentification:disconnect}

pc_demandeur_projetprofessionnel:
    path: /projetpro
    defaults : {_controller: PCDemandeurBundle:Projetpro:projet}